spring:
  profiles:
    active: development
  application:
    name: "%APP_NAME%"
    version: "%APP_VERSION%"
    build:
      time: "%APP_BUILD_TIME%"
      os:
        name: "%APP_BUILD_OS_NAME%"
        version: "%APP_BUILD_OS_VERSION%"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

jwt:
  public-key: cert/public_key.pem

---
###############################
### Development environment ###
###############################
spring:
  config:
    activate:
      on-profile: development

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: password

account-registry:
  url: http://localhost:9050

device-registry:
  url: http://localhost:9010

---
##########################
### Docker environment ###
##########################
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: password

account-registry:
  url: http://AccountRegistry:8080

device-registry:
  url: http://DeviceRegistry:8080

---
##############################
### Production environment ###
##############################
spring:
  config:
    activate:
      on-profile: production
